.\" $OpenBSD$
.\"
.\"Copyright (c) 2018 David Dahlberg <dyn+code@dahlberg.cologne>
.\"
.\"Permission to use, copy, modify, and distribute this software for any
.\"purpose with or without fee is hereby granted, provided that the above
.\"copyright notice and this permission notice appear in all copies.
.\"
.\"THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\"WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\"MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\"ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\"WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\"ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\"OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate: May 25 2018 $
.Dt QOS 1
.Os
.Sh NAME
.Nm qos
.Nd show infos about dscp and tos values
.Sh SYNOPSIS
.Nm
.Ar value
.Sh DESCRIPTION
.Nm
decodes dscp and tos values and converts values between the different
interpretations and encodings.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Ar value
The argument
.Ar value
can either be a TOS value in hexadecimal notation (0xb8), a DSCP value
in decimal notation (46) or an IANA-registered codepoint name (EF).
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Dl $ qos 0xb8
.Sh HISTORY
The
.Nm
utility has been available since 2018.
.Sh AUTHORS
.An David Dahlberg Aq Mt dyn+code@dahlberg.cologne
